export const VALUE_LENGTH = {
	LOGIN_NAME: 30,
	PASSWORD: 16,
	NICK_NAME: 16,
	VID: 4
};

export const RESPONSE_CODES = {
	SUCCESS: 0,
	MANAGER_ALREADY_IN_CHANNEL: 301,
	PERMISSION_DENIED: 302,
	LEVEL_NOT_ENOUGH: 303,
	REPEAT_LOGIN: 304
};

export const USER_STATE = {
	IDOL: 0,
	CONNECTING: 1,
	CONNECTED: 2,
	WAITING_MANAGER: 3,
	CHANGE_ANCHOR: 4,
	CHANGE_DEALER: 5,
	CHANGE_TABLE: 6,
	ANNOYING: 7,
	ADVERTISEMENT: 8
};

export const MANAGER_ACTIONS = {
	JOIN_CHANNEL: 0,
	LEAVE_CHANNEL: 1,
	MUTE_CLIENT: 2,
	UNMUTE_CLIENT: 3,
	MUTE_ANCHOR: 4,
	UNMUTE_ANCHOR: 5,
	KICKOUT_CLIENT: 6,
	BLACKLIST_CLIENT: 7
};

export const MUTE_STATE = {
	MUTE: 0,
	UNMUTE: 1
};

export const DATA_SERVER_VALUE_LENGTH = {
	VL_VIDEO_ID: 4,
	VL_USER_NAME: 30,
	VL_PSW: 16,
	VL_NICK_NAME: 16,
	VL_CURRENCY: 6,
	VL_DEALER_CODE: 8,
	VL_GAME_CODE: 14,
	VL_GM_TYPE: 4,
	VL_TIMESTAMP: 19,
	VL_BILL_NO: 16,
	VL_TBL_CODE: 4,
	VL_BANKER: 3,
	VL_PLAYER: 3
};

export const ROLE = {
	NORMAL: 0,
	ADMIN: 1
};

export const CONTRACT_MODE = {
	OWNER: 0,
	SHARE: 1
};

export const MANAGER_ACTION_TYPE = {
	KICKOUT_CLIENT: 'kickout',
	BLACKLIST_CLIENT: 'blacklist'
}

export const DATA_SERVER_VIDEO_STATUS = {
	FREE: 0,	//空闲
	CONTRACTED: 1,	//包桌
	LOCKED: 2,	//已锁
	OTHER_LOCKED: 3,	//已锁
	TURN_CARD: 4,	//竞眯
	UNKNOWN: 5
}

export const DATA_SERVER_GAME_STATUS = {
	CLOSED: 0,	//游戏关闭
	CAN_BET: 1,	//下注状态
	DISPATCH_CARD: 2,	//正在发牌
	LAST_CALL: 3,
	TURN_CARD: 10,	//正在眯牌
	NEW_SHOE: 11,	//洗牌
	PAUSE_BET: 12,	//暂停下注
	UNKNOWN: 13
};