export const VALUE_LENGTH = {
	LOGIN_NAME: 30,
	PASSWORD: 16,
	NICK_NAME: 16,
	VID: 4
};

export const RESPONSE_CODES = {
	SUCCESS: 0,
	MANAGER_ALREADY_IN_CHANNEL: 1,
	PERMISSION_DENIED: 2
};

export const USER_STATE = {
	IDOL: 0,
	CONNECTING: 1,
	CONNECTED: 2,
	WAITING_MANAGER: 3
};

export const MANAGER_ACTIONS = {
	JOIN_CHANNEL: 0,
	LEAVE_CHANNEL: 1,
	MUTE_CLIENT: 2,
	UNMUTE_CLIENT: 3,
	MUTE_ANCHOR: 4,
	UNMUTE_ANCHOR: 5,
	KICKOUT_CLIENT: 6,
	BLACKLIST_CLIENT: 7
};

export const MUTE_STATE = {
	MUTE: 0,
	UNMUTE: 1
};