export const VALUE_LENGTH = {
	LOGIN_NAME: 30,
	PASSWORD: 16,
	NICK_NAME: 16,
	VID: 4
};

export const RESPONSE_CODES = {
	SUCCESS: 0,
	MANAGER_ALREADY_IN_CHANNEL: 301,
	PERMISSION_DENIED: 302,
	LEVEL_NOT_ENOUGH: 303,
	REPEAT_LOGIN: 304
};

export const USER_STATE = {
	IDOL: 0,
	CONNECTING: 1,
	CONNECTED: 2,
	WAITING_MANAGER: 3
};

export const MANAGER_ACTIONS = {
	JOIN_CHANNEL: 0,
	LEAVE_CHANNEL: 1,
	MUTE_CLIENT: 2,
	UNMUTE_CLIENT: 3,
	MUTE_ANCHOR: 4,
	UNMUTE_ANCHOR: 5,
	KICKOUT_CLIENT: 6,
	BLACKLIST_CLIENT: 7
};

export const MUTE_STATE = {
	MUTE: 0,
	UNMUTE: 1
};

export const DATA_SERVER_VALUE_LENGTH = {
	VL_VIDEO_ID: 4,
	VL_USER_NAME: 30,
	VL_PSW: 16
};

export const ROLE = {
	NORMAL: 0,
	ADMIN: 1
};