export const SET_VOICE_APP_ID = 'SET_VOICE_APP_ID';
export const SET_CHANNEL_LIST = 'SET_CHANNEL_LIST';
export const SET_CURRENT_CHANNEL_ID = 'SET_CURRENT_CHANNEL_ID';
export const SET_CHANNEL_JOIN_STATUS = 'SET_CHANNEL_JOIN_STATUS';